version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker
          command: |
            docker build -t registry.alexhicks.net/wasp/server:${CIRCLE_SHA1} .
            docker tag registry.alexhicks.net/wasp/server:${CIRCLE_SHA1} registry.alexhicks.net/wasp/server:latest
      - run:
          name: Deploy Docker
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin https://registry.alexhicks.net
            docker push registry.alexhicks.net/wasp/server:${CIRCLE_SHA1}
            docker push registry.alexhicks.net/wasp/server:latest
